### ISSUE TITLE
No manifest file present?

### ISSUE THREAD

**Issue by thegsi** [koalabears/koalabears.github.io#56]
Readme file is a little limited too.

**Comment by mk4111** [comment]
Googled a bit and also spoke to Nelson about how to create a manifest file because I couldn't really figure it out. Found out that it isn't really necessary for our first project because we don't have dependencies, and that we would only start to need a manifest file or a .json file once we start using node.js, and when we have APIs. 

I'll go add a bit to the Readme file in a jiffy!

**Comment by mk4111** [comment]
If you're happy with the answer, please could I ask you to close the issue? Thanks!
